# Generated by Django 2.1.2 on 2018-10-22 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Infodate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probeg_tek', models.CharField(max_length=8)),
                ('date_create', models.DateTimeField(verbose_name='дата приобретения')),
                ('probeg_all', models.CharField(max_length=8)),
                ('date_publish', models.DateTimeField(verbose_name='дата публикации')),
                ('conder', models.CharField(max_length=3)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
