# Generated by Django 2.1.2 on 2018-10-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Infodate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infodate',
            name='type_expl',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infodate',
            name='conder',
            field=models.CharField(choices=[('да', 'да'), ('нет', 'нет')], default='да', max_length=3),
        ),
        migrations.AlterField(
            model_name='infodate',
            name='date_create',
            field=models.DateTimeField(verbose_name='Дата приобретения'),
        ),
        migrations.AlterField(
            model_name='infodate',
            name='date_publish',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
