# Generated by Django 2.1.2 on 2018-10-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Infodate', '0002_auto_20181029_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infodate',
            name='type_expl',
            field=models.CharField(choices=[('новый', 'новый'), ('б/у', 'б/у')], default='новый', max_length=5),
        ),
    ]
