# Generated by Django 2.1.2 on 2018-10-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Infodate', '0003_auto_20181029_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='infodate',
            name='type_engine',
            field=models.CharField(choices=[('новый', 'новый'), ('б/у', 'б/у')], default='новый', max_length=5),
        ),
    ]
