# Generated by Django 2.1.2 on 2018-10-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Infodate', '0004_infodate_type_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='infodate',
            name='type_kpp',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infodate',
            name='type_engine',
            field=models.CharField(choices=[('K7J', '1,4л/75л.с.(K7J)'), ('K7M710', '1,6л/86л.с.(K7M710)'), ('K7M800', '1,6л/102л.с.(K7M800)')], default='K7J', max_length=20),
        ),
    ]
