# Generated by Django 2.1.2 on 2018-10-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Infodate', '0005_auto_20181029_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='infodate',
            name='date_oil_last',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='infodate',
            name='type_engine',
            field=models.CharField(choices=[('K7J', '1,4л/75л.с.(K7J)'), ('K7M710', '1,6л/86л.с.(K7M710)'), ('K7M800', '1,6л/102л.с.(K7M800)'), ('K7M801', '1,6л/113л.с.')], default='K7J', max_length=20),
        ),
        migrations.AlterField(
            model_name='infodate',
            name='type_kpp',
            field=models.CharField(choices=[('akpp', 'АКПП'), ('mkpp', 'МКПП')], default='mkkp', max_length=5),
        ),
    ]
