# Generated by Django 2.1.2 on 2018-10-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Infodate', '0006_auto_20181029_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infodate',
            name='date_create',
        ),
        migrations.AddField(
            model_name='infodate',
            name='date_creat',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='infodate',
            name='date_oil_last',
            field=models.DateField(),
        ),
    ]
