# Generated by Django 2.1.2 on 2018-10-29 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Infodate', '0007_auto_20181029_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infodate',
            old_name='date_creat',
            new_name='date_create',
        ),
    ]
