# Generated by Django 2.1.2 on 2018-10-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Infodate', '0009_auto_20181029_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='infodate',
            name='to_make',
            field=models.CharField(choices=[('да', 'да'), ('нет', 'нет')], default='да', max_length=3),
        ),
        migrations.AlterField(
            model_name='infodate',
            name='date_brake_last',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='infodate',
            name='date_liq_last',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='infodate',
            name='date_to_last',
            field=models.DateField(),
        ),
    ]
