# Generated by Django 2.1.2 on 2018-11-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Infodate', '0010_auto_20181029_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infodate',
            name='type_engine',
            field=models.CharField(choices=[('K7J', '1,4л/75л.с.(K7J)'), ('K7M7101', '1,6л/82л.с.(K7M710)'), ('K7M710', '1,6л/86л.с.(K7M710)'), ('K7M800', '1,6л/102л.с.(K7M800)'), ('K7M801', '1,6л/113л.с.')], default='K7J', max_length=20),
        ),
        migrations.AlterField(
            model_name='infodate',
            name='type_kpp',
            field=models.CharField(choices=[('akpp', 'АКПП'), ('mkpp', 'МКПП')], default='mkkp', max_length=4),
        ),
    ]
